version: "3.8"

services:
  db:
    container_name: db-composed
    image: mongo:${MONGO_VERSION}
    networks:
      - net_A
    volumes:
      - mongodata:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  server:
    container_name: server
    image: shai3/express-mongodb-app:latest
    networks:
      - net_A
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db-composed:27017/mydatabase

    depends_on:
      - db

networks:
  net_A:
    external: false
    name: net_A

volumes:
  mongodata:
